modLoader = "javafml"
loaderVersion = "[38,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/SteveKunG-Lib/issues"

[[mods]]
modId = "stevekung_lib"
version = "${version}"
displayName = "SteveKunG's Lib"
description = "Code and Utilities for SteveKunG's mods!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/stevekungs-lib"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/stevekung's_lib_version.json"
logoFile = "logo.png"
authors = "SteveKunG"

[[dependencies.stevekung_lib]]
modId = "forge"
mandatory = true
versionRange = "[38.0.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stevekung_lib]]
modId = "architectury"
mandatory = true
versionRange = "[3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stevekung_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"