modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"
issueTrackerURL = "https://github.com/SteveKunG/SteveKunG-Lib/issues"

[[mods]]
modId = "stevekungs_lib"
version = "${version}"
displayName = "SteveKunG's Lib"
description = "Code and Utilities for SteveKunG's mods!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/stevekungs-lib"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/stevekung's_lib_version.json"
logoFile = "logo.png"
authors = "SteveKunG"

[[dependencies.stevekungs_lib]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stevekungs_lib]]
modId = "architectury"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stevekungs_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"