import com.gtnewhorizons.retrofuturagradle.mcp.InjectTagsTask
import org.jetbrains.gradle.ext.Gradle
import org.codehaus.groovy.runtime.MethodClosure
import groovy.text.SimpleTemplateEngine

plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.4.1"
    id "com.gtnewhorizons.retrofuturagradle" version "1.4.6"
    id "io.github.CDAGaming.cursegradle" version "1.6.1"
    id "maven-publish"
}

ext.interpolate = this.&interpolate as MethodClosure

String interpolate(String value) {
    if (value.startsWith('${{') && value.endsWith('}}')) {
        value = value.substring(3, value.length() - 2)
        Binding newBinding = new Binding(this.binding.getVariables())
        newBinding.setProperty('it', this)
        return new GroovyShell(this.getClass().getClassLoader(), newBinding).evaluate(value)
    }
    if (value.contains('${')) {
        return new SimpleTemplateEngine().createTemplate(value).make(project.properties).toString()
    }
    return value
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
        vendor.set(JvmVendorSpec.AZUL)
    }
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

minecraft {
    mcVersion.set(minecraft_version)

    mcpMappingChannel.set(mapping_channel)
    mcpMappingVersion.set(mapping_version)

    if (project.hasProperty("username")) {
        username.set(project.username)
    } else {
        username.set("Developer")
    }

    useDependencyAccessTransformers.set(true)

    // Add various JVM arguments here for runtime
    def args = ["-ea:" + group]

    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        args << "-Dmixin.debug=true"
        args << "-Dmixin.debug.verbose=true"
        args << "-Dmixin.hotSwap=true"
        args << "-Dmixin.checks.interfaces=true"
        args << "-Dmixin.debug.export=true"
    }
    extraRunJvmArguments.addAll(args)

    if (file("tags.properties").exists()) {
        Properties props = new Properties().tap {  it.load(file("tags.properties").newInputStream()); it }
        if (!props.isEmpty()) {
            injectedTags.set(props.collectEntries { k, v -> [(k): interpolate(v)] })
        }
    }
}

// Adds Access Transformer files to tasks
def fileLocation = file("${projectDir}/src/main/resources/META-INF/stevekung_lib_at.cfg")
if (fileLocation.exists()) {
    tasks.deobfuscateMergedJarToSrg.accessTransformerFiles.from(fileLocation)
    tasks.srgifyBinpatchedJar.accessTransformerFiles.from(fileLocation)
} else {
    throw new GradleException("Access Transformer file [$fileLocation] does not exist!")
}

repositories {
    maven {
        name = "CleanroomMC Maven"
        url = "https://maven.cleanroommc.com"
    }
    mavenLocal()
}

dependencies {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        String mixin = modUtils.enableMixins("zone.rong:mixinbooter:${mixin_booter_version}", "mixins.${mod_id}.refmap.json")
        api(mixin) {
            transitive = false
        }
        annotationProcessor "org.ow2.asm:asm-debug-all:5.2"
        annotationProcessor "com.google.guava:guava:32.1.2-jre"
        annotationProcessor "com.google.code.gson:gson:2.8.9"
        annotationProcessor(mixin) {
            transitive = false
        }
    }
}

processResources {
    inputs.property "mod_id", mod_id
    inputs.property "mod_version", mod_version
    inputs.property "display_name", display_name
}

idea {
    module {
        inheritOutputDirs = true
    }
    project {
        settings {
            runConfigurations {
                "1. Run Client"(Gradle) {
                    taskNames = ["runClient"]
                }
                "2. Run Server"(Gradle) {
                    taskNames = ["runServer"]
                }
            }
            compiler.javac {
                afterEvaluate {
                    javacAdditionalOptions = "-encoding utf8"
                    moduleJavacAdditionalOptions = [
                            (project.name + ".main"): tasks.compileJava.options.compilerArgs.collect { '"' + it + '"' }.join(" ")
                    ]
                }
            }
        }
    }
}

String fileName = "${archives_base_name}-mc${minecraft_version}"
Map<String, ?> customAttributes = [
        "FMLAT": "stevekung_lib_at.cfg",
        "FMLCorePlugin": "com.stevekung.lib.core.SteveKunGLibPlugin",
        "FMLCorePluginContainsFMLMod": true,
        "ForceLoadAsMod": true
]

jar {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        manifest {
            attributes(customAttributes)
        }
    }

    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
    from sourceSets.main.output
}

tasks.register("sourcesJar", Jar) {
    from sourceSets.main.allSource
    archiveBaseName = fileName
    archiveClassifier = "sources"
    archiveVersion = "v${mod_version}"
}

tasks.register("deobfJar", Jar) {
    from sourceSets.main.output
    manifest {
        attributes(customAttributes)
    }
    archiveBaseName = fileName
    archiveClassifier = "deobf"
    archiveVersion = "v${mod_version}"
}

tasks.named("injectTags", InjectTagsTask).configure {
    onlyIf {
        return !it.getTags().get().isEmpty()
    }
    it.outputClassName.set("${maven_group}.core.Tags")
}

artifacts {
    archives sourcesJar
    archives deobfJar
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_API_TOKEN") ?: ""
    project {
        id = curseforge_project_id
        changelog = rootProject.file("CHANGE_LOG.md")
        changelogType = "markdown"
        releaseType = release_type
        addGameVersion "Forge"
        addGameVersion minecraft_version

        if (project.hasProperty("curseforge_additional_game_versions") && !curseforge_additional_game_versions.isEmpty()) {
            curseforge_additional_game_versions.split(",").each {
                String gameVersion -> addGameVersion gameVersion
            }
        }

        mainArtifact(reobfJar) {
            it.displayName = "[Forge ${minecraft_version}] ${display_name} v${mod_version}"
        }

        if (project.hasProperty("curseforge_forge_required_dependencies") && !curseforge_forge_required_dependencies.isEmpty()
                || project.hasProperty("curseforge_forge_optional_dependencies") && !curseforge_forge_optional_dependencies.isEmpty()
                || project.hasProperty("curseforge_forge_embedded_dependencies") && !curseforge_forge_embedded_dependencies.isEmpty()
        ) {
            relations {
                if (project.hasProperty("curseforge_forge_required_dependencies") && !curseforge_forge_required_dependencies.isEmpty()) {
                    curseforge_forge_required_dependencies.split(",").each {
                        String dep -> it.requiredDependency dep
                    }
                }
                if (project.hasProperty("curseforge_forge_optional_dependencies") && !curseforge_forge_optional_dependencies.isEmpty()) {
                    curseforge_forge_optional_dependencies.split(",").each {
                        String dep -> it.optionalDependency dep
                    }
                }
                if (project.hasProperty("curseforge_forge_embedded_dependencies") && !curseforge_forge_embedded_dependencies.isEmpty()) {
                    curseforge_forge_embedded_dependencies.split(",").each {
                        String dep -> it.embeddedLibrary dep
                    }
                }
            }
        }

        afterEvaluate {
            uploadTask.dependsOn(reobfJar)
        }
    }
    options {
        debug = upload_debug.toBoolean()
        forgeGradleIntegration = false
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = maven_group
            artifactId = archives_base_name
            version = "mc${minecraft_version}-v${mod_version}"

            from components.java
        }
    }
}