import org.jetbrains.gradle.ext.Gradle

plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.9"
    id "com.gtnewhorizons.retrofuturagradle" version "1.4.1"
    id "io.github.CDAGaming.cursegradle" version "1.6.1"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)
java.toolchain.vendor.set(JvmVendorSpec.AZUL)

configurations {
    embed
    implementation.extendsFrom(embed)
}

minecraft {
    mcVersion.set(minecraft_version)

    mcpMappingChannel.set(mapping_channel)
    mcpMappingVersion.set(mapping_version)

    if (project.hasProperty("username")) {
        username.set(username)
    } else {
        username.set("Developer")
    }

    useDependencyAccessTransformers.set(true)

    // Add various JVM arguments here for runtime
    def args = ["-ea:" + group]

    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        args << "-Dmixin.debug=true"
        args << "-Dmixin.debug.verbose=true"
        args << "-Dmixin.hotSwap=true"
        args << "-Dmixin.checks.interfaces=true"
        args << "-Dmixin.debug.export=true"
    }
    extraRunJvmArguments.addAll(args)
}

// Adds Access Transformer files to tasks
def fileLocation = file("${projectDir}/src/main/resources/META-INF/stevekung_lib_at.cfg")
if (fileLocation.exists()) {
    tasks.deobfuscateMergedJarToSrg.accessTransformerFiles.from(fileLocation)
    tasks.srgifyBinpatchedJar.accessTransformerFiles.from(fileLocation)
} else {
    throw new GradleException("Access Transformer file [$fileLocation] does not exist!")
}

repositories {
    maven {
        name = "CleanroomMC Maven"
        url = "https://maven.cleanroommc.com"
    }
    mavenLocal()
}

dependencies {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        String mixin = modUtils.enableMixins("zone.rong:mixinbooter:${mixin_booter_version}", "mixins.${mod_id}.refmap.json")
        api(mixin) {
            transitive = false
        }
        annotationProcessor "org.ow2.asm:asm-debug-all:5.2"
        annotationProcessor "com.google.guava:guava:32.1.2-jre"
        annotationProcessor "com.google.code.gson:gson:2.8.9"
        annotationProcessor(mixin) {
            transitive = false
        }
    }
}

idea {
    module {
        inheritOutputDirs = true
    }
    project {
        settings {
            runConfigurations {
                "1. Run Client"(Gradle) {
                    taskNames = ["runClient"]
                }
                "2. Run Server"(Gradle) {
                    taskNames = ["runServer"]
                }
            }
            compiler.javac {
                afterEvaluate {
                    javacAdditionalOptions = "-encoding utf8"
                    moduleJavacAdditionalOptions = [
                            (project.name + ".main"): tasks.compileJava.options.compilerArgs.collect { '"' + it + '"' }.join(' ')
                    ]
                }
            }
        }
    }
}

String fileName = "${archives_base_name}-mc${minecraft_version}"
Map<String, ?> customAttributes = [
        "FMLAT": "stevekung_lib_at.cfg",
        "FMLCorePlugin": "com.stevekung.lib.core.SteveKunGLibPlugin",
        "FMLCorePluginContainsFMLMod": true,
        "ForceLoadAsMod": true
]

jar {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        manifest {
            attributes(customAttributes)
        }
    }

    archiveVersion = "v${mod_version}"
    archiveBaseName = fileName
    from sourceSets.main.output
}

tasks.register("sourcesJar", Jar) {
    from sourceSets.main.allSource
    archiveBaseName = fileName
    archiveClassifier = "sources"
    archiveVersion = "v${mod_version}"
}

tasks.register("deobfJar", Jar) {
    from sourceSets.main.output
    manifest {
        attributes(customAttributes)
    }
    archiveBaseName = fileName
    archiveClassifier = "deobf"
    archiveVersion = "v${mod_version}"
}

artifacts {
    archives sourcesJar
    archives deobfJar
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = maven_group
            artifactId = archives_base_name
            version = "mc${minecraft_version}-v${mod_version}"

            from components.java
        }
    }
}