# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configureondemand=true
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=1.12.2
mapping_channel=stable
mapping_version=39

# mod
display_name=SteveKunG's Lib
archives_base_name=stevekung-lib
mod_id=stevekung_lib
mod_description=A common library used by SteveKunG's mods
maven_group=com.stevekung.lib
mod_version=1.4.0
release_type=release
mixin_booter_version=10.6

# curseforge
curseforge_project_id=296019

# modrinth
modrinth_project_id=stevekung-lib