package com.stevekung.lib.core;

import java.util.Collections;

import net.minecraft.launchwrapper.Launch;
import net.minecraftforge.common.config.Config;
import net.minecraftforge.common.config.ConfigManager;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import com.stevekung.lib.client.event.ClientEventHandler;
import com.stevekung.lib.utils.ColorUtils;
import com.stevekung.lib.utils.CommonUtils;
import com.stevekung.lib.utils.LoggerSL;
import com.stevekung.lib.utils.client.ClientUtils;

@Mod(modid = Tags.MOD_ID, name = Tags.MOD_NAME, version = Tags.VERSION, dependencies = SteveKunGLib.FORGE_VERSION, updateJSON = SteveKunGLib.JSON_URL)
public class SteveKunGLib
{
    protected static final String FORGE_VERSION = "required-after:mixinbooter@[10.6,); after:forge@[14.23.5.2847,);";
    protected static final String JSON_URL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/stevekung's_lib_version.json";
    private static final String URL = "https://www.curseforge.com/minecraft/mc-mods/stevekung-lib";
    public static boolean isDevelopment;

    static
    {
        try
        {
            SteveKunGLib.isDevelopment = Launch.classLoader.getClassBytes("net.minecraft.world.World") != null;
        }
        catch (Exception e)
        {
            LoggerSL.error("Couldn't get development environment", e);
        }
    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        SteveKunGLib.init(event.getModMetadata());
        CommonUtils.registerEventHandler(this);

        if (ClientUtils.isEffectiveClient())
        {
            CommonUtils.registerEventHandler(new ClientEventHandler());
        }
    }

    @EventHandler
    public void init(FMLInitializationEvent event)
    {

    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
        if (ClientUtils.isEffectiveClient())
        {
            ColorUtils.init();
        }
    }

    @SubscribeEvent
    public void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent event)
    {
        if (event.getModID().equals(Tags.MOD_ID))
        {
            ConfigManager.sync(Tags.MOD_ID, Config.Type.INSTANCE);
        }
    }

    private static void init(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = Tags.MOD_ID;
        info.name = Tags.MOD_NAME;
        info.version = Tags.VERSION;
        info.url = SteveKunGLib.URL;
        info.updateJSON = SteveKunGLib.JSON_URL;
        info.description = "A common library used by SteveKunG's mods";
        info.authorList = Collections.singletonList("SteveKunG");
    }
}